title: [Lead Sheet Generation and Arrangement]
description: [AI Loop Generator for Composer's reference]
#logo: /AI Loops.png
#kramdown: Music and Audio Computing Lab
#kramdown: Research Center for IT Innovation
#kramdown: Academia Sinica
theme: jekyll-theme-minimal
